apiVersion: batch/v1
kind: Job
metadata:
  name: test
spec:
  template:
    spec:
      containers:
      - name: run-command
        image: alpine
        command: ["{{ .Values.command }}",  "{{ .Values.argument }}"]
      restartPolicy: Never
  backoffLimit: 4
