apiVersion: batch/v1
kind: Job
metadata:
  name: test-{{ .Values.jobNameSuffix }}-foo
spec:
  template:
    spec:
      containers:
      - name: run-command
        image: alpine
        command: ["exit",  "1"]
      restartPolicy: Never
  backoffLimit: 4
